### ISSUE TITLE
Debug output during Cap run

### ISSUE THREAD

**Issue by mhoran** [gofullstack/capistrano-chef#13]
It seems that something in upstream Chef broke setting the verbosity level.  I'm guessing https://github.com/opscode/chef/commit/c1440a6ec2d0393b9e0da87974903300e207c80d has something to do with it.

**Comment by smith** [comment]
Thanks for reporting this. I actually had this happening originally and figured out how to make it go away, but I think a capistrano-chef release (maybe from pull #12) broke it. I can look into it and get back the original behavior.

**Comment by rafaelmagu** [comment]
Any updates?

**Comment by smith** [comment]
Opened a pull for this. Will merge shortly unless anyone notices problems.

**Comment by smith** [comment]
Should be fixed now. Please reopen if you still have problems.
