### ISSUE TITLE
Need a better way to set db master automatically

### ISSUE THREAD

**Issue by akatz** [gofullstack/capistrano-chef#16]
The db role is for running migrations as far as I understand it. To do this at the moment I have an empty chef role on my chef server for db_master which i apply to one of my webservers, that I search on and use to set the db master. It would be nice to have a way to tell it to pick one of the webservers and use it to run migrations.

**Comment by smith** [comment]
Thanks for the idea. What kind of way did you have in mind? I've just been using

```
chef_role :db, 'roles:web', limit: 1, primary: true
```

Are you thinking something like:

```
chef_role :db, random_single_node_from(:web)
```

Where `:web` is a previously defined `chef_role`?

I'd like to avoid too much magic, as a lot of people use Capistrano for more than just Rails deployments and I want to keep it simple. Let me know what would make this better for you.

**Comment by smith** [comment]
Closing this. Please reopen if you have more ideas or think it needs a better response. Thanks!

**Comment by akatz** [comment]
Sorry for the delay in response. Thanks for the advice.
