### ISSUE TITLE
ec2 public_hostnames

### ISSUE THREAD

**Issue by luntzel** [gofullstack/capistrano-chef#17]
How would I populate the chef_role entries with ec2 public_hostname data? Or am I thinking about this the wrong way?

**Comment by smith** [comment]
You should be able to do this with a Proc:

```
chef_role :web, '*:*', :attribute => Proc.new do |n|
  n['cloud']['public_hostname']
end
```

There's a more complex example in the readme: https://github.com/cramerdev/capistrano-chef#examples

Let me know if that doesn't work for you, or if there's anything that would make it clearer either in the docs or the API. Thanks!

**Comment by luntzel** [comment]
Not to assume this should just work copy and paste, but I keep getting: 

./config/deploy.rb:24:in `new': tried to create Proc object without a block (ArgumentError)

with that code, as well as fiddling around with the expanded example on the readme. I can see that the attribute I need is node['ec2']['public_hostname']. 

However, this returned the private IP addresses correctly:

chef_role :web, 'roles:web', :attribute => { :eth0 => :inet }

Thanks for your help!

**Comment by smith** [comment]
Ruby can sometimes be picky about blocks and precedence, something like `Proc.new( { |n| ... } )` might work too.

**Comment by luntzel** [comment]
Ah. This ended up working:

chef_role :web, 'roles:web', :attribute => Proc.new { |n| n['ec2']['public_hostname'] }

Thanks again!
