### ISSUE TITLE
Fails when chef query returns a nil entry

### ISSUE THREAD

**Issue by dpnsan** [gofullstack/capistrano-chef#19]
Chef::Search::Query#search can return nil rows, causing Capistrano::Chef.search_nodes to fail with:

```
capistrano-chef-0.0.7/lib/capistrano/chef.rb:29:in `search_chef_nodes': undefined method `[]' for nil:NilClass (NoMethodError)
```

Looking at Chef::Search::Query#search, nils are handled gracefully, leading me to believe that this may have come up for others.

**Comment by smith** [comment]
Fixed in #20 :+1:
