### ISSUE TITLE
Launching Capistrano when a new Chef node is bootstrapping fails

### ISSUE THREAD

**Issue by rafaelmagu** [gofullstack/capistrano-chef#21]
Currently, we have Amazon automatically launching and terminating instances. When a new instance is launched, our bootup script bootstraps the instance with Chef. However, if a user tries to open a Capistrano session with capistrano-chef installed during the bootstrap period, the following error appears:

```
/Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.15.5/lib/capistrano/server_definition.rb:16:in `initialize': undefined method `match' for nil:NilClass (NoMethodError)
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.15.5/lib/capistrano/configuration/roles.rb:57:in `new'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.15.5/lib/capistrano/configuration/roles.rb:57:in `block in role'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.15.5/lib/capistrano/configuration/roles.rb:57:in `each'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.15.5/lib/capistrano/configuration/roles.rb:57:in `role'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-chef-0.0.8/lib/capistrano/chef.rb:59:in `chef_role'
    from Capfile:12:in `load'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.15.5/lib/capistrano/configuration/loading.rb:93:in `instance_eval'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.15.5/lib/capistrano/configuration/loading.rb:93:in `load'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.15.5/lib/capistrano/configuration/loading.rb:180:in `load_from_file'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.15.5/lib/capistrano/configuration/loading.rb:89:in `load'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.15.5/lib/capistrano/configuration/loading.rb:86:in `block in load'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.15.5/lib/capistrano/configuration/loading.rb:86:in `each'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.15.5/lib/capistrano/configuration/loading.rb:86:in `load'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:65:in `block in load_recipes'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:65:in `each'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:65:in `load_recipes'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:31:in `execute!'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:14:in `execute'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.15.5/bin/cap:4:in `<top (required)>'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/bin/cap:23:in `load'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/bin/cap:23:in `<main>'
```

This seems to be because during the bootstrap period the node is created in Chef, but has no attributes set (node is only saved at the end of the run).

**Comment by smith** [comment]
Thanks for reporting this! I'll try to reproduce this and fix it or at least make it fail more gracefully. Could you please provide an example of a `cap` command and its arguments you're supplying when this happens?

**Comment by rafaelmagu** [comment]
This happens with any Capistrano command. Even `cap -T` or `cap shell`

**Comment by smith** [comment]
So either I don't understand this use case well enough or I don't think it's something that can be fixed. If a node is not bootstrapped, it's not going to show up in a search nor have any attributes. I don't see a way to fix this in capistrano-chef.

If I'm way off or if you have a plan to make this work, please reopen, and thanks again for reporting it!

**Comment by rafaelmagu** [comment]
Ok, let me tell you a story:

Here at our company, we run instances on EC2 that are automatically launched by AWS using their AutoScaling feature. We have created a custom bootstrap script for AS to run upon instance boot-up that automatically runs Chef. Our bootstrap takes about 6 minutes. During those 6 minutes, the node appears in Chef (knife node list), but doesn't have any metadata in it yet.

If during these 6 minutes I decide to launch Capistrano to work on existing servers, it fails with the error listed above.

**Comment by smith** [comment]
Thanks for the details. Reopening and will research and try to fix the error.

**Comment by jwreagor** [comment]
I realize this is almost a year later but I figured I'd leave a notice for another wandering soul...

This isn't a capistrano-chef issue. It's actually expected Chef behavior for any node running chef-client on it. The only data and attributes you will get in your node object on your Chef server prior to your first convergence is anything you uploaded for your node object to your Chef server **before** your initial chef-client run.

This is why a majority of Chef users only use Chef for deployments and skip Capistrano. Personally, I use Chef to boot everything including the git repo on initial chef-client runs. I use Capistrano::Chef for managing revisions, patches, consoles, logging, bug fixes, etc. after an initial Chef run. Which is actually why I'm hoping to provide more features for capistrano-chef users like me, who actually use the two together in a less classical way (either/or). Capistrano 3 and sshkit are great libraries!

**Comment by rafaelmagu** [comment]
@cheapRoc makes perfect sense. No point in leaving this open.

**Comment by T0MM0R** [comment]
I was getting an error just like this and discovered it was because Capistrano was trying to deploy to instances that were terminated by the autoscaling group.
