### ISSUE TITLE
Capistrano 3 and chef: undefined method `instance' for Capistrano::Configuration:Class

### ISSUE THREAD

**Issue by xdmx** [gofullstack/capistrano-chef#22]
Hi, I'm setting capistrano and chef, but when I run a simple command as rails g --help, this is the result. I'm using the last version of capistrano, capistrano-chef and capistrano-rails.

```
/home/user/.rvm/gems/ruby-2.0.0-p247@project/gems/capistrano-chef-0.0.8/lib/capistrano/chef.rb:81:in `<top (required)>': undefined method `instance' for Capistrano::Configuration:Class (NoMethodError)
        from /home/user/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:81:in `require'
        from /home/user/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:81:in `rescue in block in require'
        from /home/user/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:66:in `block in require'
        from /home/user/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `each'
        from /home/user/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `require'
        from /home/user/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler.rb:132:in `require'
        from /home/user/Projects/project/config/application.rb:7:in `<top (required)>'
        from /home/user/.rvm/gems/ruby-2.0.0-p247@project/gems/railties-4.0.0/lib/rails/commands.rb:44:in `require'
        from /home/user/.rvm/gems/ruby-2.0.0-p247@project/gems/railties-4.0.0/lib/rails/commands.rb:44:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by smith** [comment]
Thanks for reporting this! I don't think I've tested this with Capistrano 3, so that needs to be done.

There was a [similar issue on rvm-capistrano](https://github.com/wayneeseguin/rvm-capistrano/commit/301867dbbfd45f1bf124adfaa0abf6a0c17d71bf). Hopefully the fix needed here is just as trivial.

I'll look at it when I get a minute, or will merge in any pull requests that fix this.

**Comment by rafaelmagu** [comment]
Has any test been done since? Any updates on this? Are there any similar tools that can be used meanwhile?

**Comment by smith** [comment]
After looking at Capistrano 3 I've decided that I'm not going to add support for it myself. The reasons for this are:
- I'm not currently using this project day-to-day
- I've never used capistrano 3
- I'm not using capistrano at all at this time.

So, I'm going to make this more clear in the readme and gemspec, and will very gladly take any pull requests that add support or offer to take a lead role in maintaining the project.

Sorry I can't put the time into this right now, hope everybody understands.

**Comment by rafaelmagu** [comment]
Fair enough. For the record, I have since stopped using this Gem in favor of using a bit of Ruby magic in the Capfile itself to populate my roles.

**Comment by smith** [comment]
Updated the README in fa37f919.

**Comment by rroblak** [comment]
@smith I've added support for Capistrano 3 in [PR 23](https://github.com/cramerdev/capistrano-chef/pull/23).  You'll see that I also removed a bunch of stuff that I didn't feel like bothering with converting to Cap 3 right now.

I'm also happy to offer to maintain this project as I'll be using it for the foreseeable future.

**Comment by smith** [comment]
Thanks! Closing this in favor of #23.
